import type { Metadata } from "next";
import '@indxsearch/intrface/styles.css';
import "./globals.css";

export const metadata: Metadata = {
  title: "indx-intrface demo application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
